[project]
name = "linkedin-query-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "questionary>=2.0.0",
  "setuptools",
]
