global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'system_metrics_collector'
    static_configs:
      - targets: ['localhost:8000']
        labels:
          service: 'smc'
          environment: 'production'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['localhost:8889']
        labels:
          service: 'otel-collector'
          environment: 'production'

  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['localhost:8888']
        labels:
          service: 'otel-collector-internal'
          environment: 'production'