name: Deploy Tag to ECR
on:
  push:
    tags:
      - '*'

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "730335278395"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SYSTEM_GITHUB_SECRET_KEY }}
  ECR_REPOSITORY_NAME: webhooks-alertmanager

permissions: write-all

jobs:
  config-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_SF_COMMON_PRIVATE_KEY }}
      - name: Adicionar github.com ao known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

  build-and-push-ecr:
    needs: config-envs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_SF_COMMON_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          platforms: linux/amd64

      - name: Create and use a new builder instance
        run: |
          docker buildx create --name mybuilder --use

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          ssh: default
          platforms: linux/amd64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.ref_name }}
          builder: mybuilder
          cache-from: |
            type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:cache
            type=gha
          cache-to: |
            type=gha,mode=max
