name: Deploy Main to ECR
on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "730335278395"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SYSTEM_GITHUB_SECRET_KEY }}
  ECR_REPOSITORY_NAME: webhooks-alertmanager

permissions: write-all

jobs:
  config-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_SF_COMMON_PRIVATE_KEY }}
      - name: Adicionar github.com ao known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

  generate-tag:
    needs: config-envs
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.bump.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout with CI-bot creds
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SF_CI_BOT_PAT }}
          persist-credentials: true
      
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Configure git user
        run: |
          git config user.name "sf-ci-bot"
          git config user.email "github-ci-bot@systemframe.com.br"

      - name: Bump version and create tag
        id: bump
        run: |
          cz bump --yes

          # Discover the new tag locally after the push
          NEW_TAG=$(git describe --tags --abbrev=0)
          echo "NEW_TAG=${NEW_TAG}"
          echo "IMAGE_TAG=${NEW_TAG}" >> $GITHUB_OUTPUT
      
      - name: Make your changes…
        run: |
          # e.g. bump version, update files, etc.
          git add .
          git diff-index --quiet HEAD || git commit -m "ci: automated update via sf-ci-bot"
          git push origin HEAD
          git push --tags

  build-and-push-ecr:
    needs: generate-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_SF_COMMON_PRIVATE_KEY }}
      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ needs.generate-tag.outputs.IMAGE_TAG }}
        with:
          context: .
          push: true
          platforms: linux/amd64
          ssh: default
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/webhooks-alertmanager:${{ needs.generate-tag.outputs.IMAGE_TAG }}
          cache-from: type=s3,region=us-east-1,bucket=buildkit-cache-systemframe-dev-us-east-1,name=buildx
          cache-to: type=s3,region=us-east-1,bucket=buildkit-cache-systemframe-dev-us-east-1,name=buildx,mode=max
